#!/usr/bin/env python3.13


from coordinates import get_gps_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    latitude = get_gps_coordinates().latitude
    longitude = get_gps_coordinates().longitude

    weather = get_weather(coordinates)
    print(format_weather(weather))
