#!/usr/bin/env python3.13

from coordinates import get_gps_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    my_coordinates = get_gps_coordinates()
    weather = get_weather(my_coordinates)
    print(format_weather(weather))
